{
 "title": "SonarQube - Executive dashboard",
 "tags": [
  "prometheus",
  "application"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "tag", "label": "Tag", "query": { "query": "sonar_tag_index" } }
  ]
 },
 "panels": [
  {
   "title": "Bugs",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_bugs{tags=~\".*$tag.*\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_vulnerabilities{tags=~\".*$tag.*\"}"
    }
   ]
  },
  {
   "title": "Code coverage (%)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sonar_line_coverage{tags=~\".*$tag.*\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_code_smells{tags=~\".*$tag.*\"}"
    }
   ]
  }
 ]
}