{
 "title": "SonarQube - Detailed dashboard",
 "tags": [
  "prometheus",
  "application"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tag", "label": "Tag", "query": { "query": "sonar_tag_index" } },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "sonar_line_coverage{tags=~\".*$tag.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Reliability rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(sonar_reliability_rating{name=~\"$project\"}[24h])"
    }
   ]
  },
  {
   "title": "Security rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(sonar_security_rating{name=~\"$project\"}[24h])"
    }
   ]
  },
  {
   "title": "Technical debt rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(sonar_sqale_rating{name=~\"$project\"}[24h])"
    }
   ]
  },
  {
   "title": "Code coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(sonar_line_coverage{name=~\"$project\"}[24h])"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Bugs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_bugs{name=~\"$project\"}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_vulnerabilities{name=~\"$project\"}"
    }
   ]
  },
  {
   "title": "Code coverage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sonar_line_coverage{name=~\"$project\"}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sonar_code_smells{name=~\"$project\"}"
    }
   ]
  }
 ]
}